# Generated by Django 3.2.4 on 2021-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('access_token', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('created_time', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_in_use', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField()),
                ('reply_count', models.PositiveIntegerField()),
            ],
        ),
    ]
