# Generated by Django 3.1.12 on 2021-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210607_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_used',
            field=models.IntegerField(default=0),
        ),
    ]
