# Generated by Django 3.1.12 on 2021-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_source',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
