# Generated by Django 3.1.12 on 2021-06-14 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210614_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 12, 53, 14, 50928)),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_used',
            field=models.DateTimeField(default=None),
        ),
    ]
