# Generated by Django 3.1.12 on 2021-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_infinite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_action_time',
            field=models.IntegerField(default=0),
        ),
    ]
