# Generated by Django 3.1.12 on 2021-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210614_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_access_token',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
