# Generated by Django 3.1.12 on 2021-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_admin_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bots_use_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='t_type',
            field=models.CharField(choices=[('like_last_n_posts', 'like_last_n_posts'), ('like_posts_list', 'like_posts_list'), ('repost', 'repost')], default=None, max_length=300),
        ),
    ]
