# Generated by Django 3.1.12 on 2021-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_last_posts_to_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='t_type',
            field=models.CharField(choices=[('like_group_last_n_posts', 'like_group_last_n_posts'), ('like_group_posts_list', 'like_group_posts_list'), ('repost', 'repost')], default=None, max_length=300),
        ),
    ]
