# Generated by Django 3.1.12 on 2021-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210614_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_action_time',
            field=models.DateTimeField(default=None),
        ),
    ]
