# Generated by Django 3.1.12 on 2021-06-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210614_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='t_type',
            field=models.CharField(choices=[('like_group_last_n_posts', 'like_group_last_n_posts'), ('like_group_posts_list', 'like_group_posts_list'), ('autopost_group_thief', 'autopost_group_thief'), ('repost', 'repost')], default=None, max_length=300),
        ),
    ]
