# Generated by Django 3.1.12 on 2021-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups_list_thief',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
